# Shapefile to GeoPackage
This Jupyter Notebook imports a custom-defined function to create a Geopackage for each shapefile folder in the 'SourceShapefiles' directory. The files are used to create a layer in the GeoPackage. The name of each layer is derived from the immediate higher-level folder.

In [1]:
from pathlib import Path
import os

# Define a variable for the project root relative path:
project_root = Path.cwd().parent

# Change the directory to the project root level:
os.chdir(project_root)

Execute the custom function:

In [ ]:
from utils.shapefile_to_gpkg import shapefile_to_gpkg

shapefile_to_gpkg(
    input_dir = project_root / 'Data' / 'SourceShapefiles',
    output_dir = project_root / 'Data' / 'GeoPackages'
)

To review the GeoPackage(s), the following For Loop displays each layer and its geometry type:

In [14]:
import geopandas as gpd
from IPython.display import display

gpkg_directory = project_root / 'Data' / 'GeoPackages'

for gpkg_path in sorted(gpkg_directory.rglob("*.gpkg")):
    print(f"GPKG Directory: {gpkg_path.relative_to(Path.cwd())}")
    print(f"{gpkg_path.stem}.gpkg Layer Name + Geometry Type:")
    
    layers = gpd.list_layers(gpkg_path)
    display(layers)

GPKG Directory: Data\GeoPackages\KingCounty.gpkg
KingCounty.gpkg Layer Name + Geometry Type:

               name geometry_type
0  CITY_KC_AREA_lyr       Polygon

GPKG Directory: Data\GeoPackages\Redmond.gpkg
Redmond.gpkg Layer Name + Geometry Type:

                                   name    geometry_type
0                                Center          Polygon
1                            Centerline  MultiLineString
2                             CityLimit          Polygon
3                  ComprehensiveLandUse          Polygon
4                         Neighborhoods          Polygon
5                                  Park     MultiPolygon
6                          PavementEdge  MultiLineString
7                                  Pond     MultiPolygon
8                                Stream       LineString
9                                 Trail  MultiLineString
10  TransitOrientedDevelopmentFocusArea          Polygon
11                               Zoning          Polygon

----- END OF NOTEBOOK ----------